### ISSUE TITLE
通信キャンセル時にonNetworkErrorが呼ばれる場合がある

### ISSUE THREAD

**Issue by akira-nakajima-snp** [Kibaan/AbstractHTTP-iOS#4]
通信をキャンセルした際に、`onCanceled`と`onNetworkError`が連続で呼ばれる場合がある。

**Comment by Kibaan** [comment]
iOS12では簡単に発生するが、iOS13では発生しづらい。

**Comment by Kibaan** [comment]
`Connection.cancel()` から以下の流れで `end(...)` が呼び出され、end内で `executionId` にnilがセットされる。

1. onCancel(executionId)
2. handleError(...)
3. mainThread { errorProcess(...) }
4. end(...)

executionIdがnilの場合、`Connection.complete` からの処理は行わないよう制御しているが、上記の3でメインスレッドへ再キューしているため、`executionId` にnilをセットするタイミングが遅くなり、通信キャンセルからの complete が先に実行されてしまいキャンセル時に `onNetworkError` も発生するものと思われる。

**Comment by Kibaan** [comment]
キャンセル時は即座に `executionId = nil` にするよう修正。
